<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{c43055ab-c7f9-4244-8b31-5d4dbf71b705}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Niet gemaakt

(*
Druktoets functies

Maak een FB DrukknopSpecial aan die een drukknop speciale functies geeft zoals

    Één enkele klik
    Dubbele klik
    Lang klikken ( > 1s )

Dit zijn natuurlijk drie aparte uitgangen en slechts één ingang.
*)]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="10" Count="7" />
      <LineId Id="9" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>