<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{f7236189-f2e9-4dfb-a883-e9d30d96e06e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
pwmInstance : FB_PWM;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[pwmInstance(fPeriod := 1000, fDutyCycle := 50); // Voorbeeldwaarden]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>