<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{3858e7b4-116a-41cb-9324-bee8c68304bb}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    fbTimer: TON;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*
Millis (1 regel code)

Maak met slechts één FB een programma dat iedere x milliseconden één enkele puls geeft.
*)

fbTimer(IN:=NOT fbTimer.Q, PT:=T#3ms); ]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="1" />
      <LineId Id="7" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="16" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>